### ISSUE TITLE
My first two suggestions

### ISSUE THREAD

**Issue by pjdevries** [astridx/meinblog#12]
First I want to pay my respect for the comprehensive J4 extension development tutorial and thank you for making it available to all of us. Today I'm making my first attempt at creating a J4 component, using your work as a guideline. Whenever I see something I think might not be correct, I'll let you know. Thus far I found the following:

In the [Preface](https://blog.astrid-guenther.de/en/joomla-tutorial-vorwort) you mention `/library/autoload_psr4.php` as the location of the PSR4 autoload file. A quick search shows there are two such files in a J4 installation
- /administrator/cache/autoload_psr4.php
- /libraries/vendor/composer/autoload_psr4.php

I assume you actually refer tothe first, which is re-created indeed when removed.

In [The first view in the backend](https://blog.astrid-guenther.de/en/die-erste-ansicht-im-backend) you mention `administrator/components/com_foos/View/Foos/HtmlView.php` as the path to the default view class. I think it misses `/src` and should be `administrator/components/com_foos/src/View/Foos/HtmlView.php`.

**Comment by astridx** [comment]
Thank you very much. You are right. The location of `autoload_psr4.php` has been changed in https://github.com/joomla/joomla-cms/pull/28436/files. I have corrected that now.

 I have also added the `src `to `administrator/components/com_foos/View/Foos/HtmlView.php`.

**Comment by astridx** [comment]
Should be fine now. See: https://github.com/astridx/meinblog/blob/master/content/posts/joomla/0vorwort.en.md#the-autoload_psr4php-file
Thank you very much @pjdevries
