### ISSUE TITLE
Menu Item and SEF

### ISSUE THREAD

**Issue by pjdevries** [astridx/meinblog#13]
In chapter [A Menu Item](https://blog.astrid-guenther.de/en/ein-menuepunkt) It might be useful to mention not to have "Search Engine Friendly URLs" enabled :)

**Comment by astridx** [comment]
What do you mean exactly? What doesn't work with search engine friendly URLs? If I see it correctly, then only the URL in the address bar of the browser is different in the final test. But everything works. Or am I missing something?

**Comment by astridx** [comment]
@pjdevries Or do you mean the "
Test your Joomla component" 
in https://blog.astrid-guenther.de/en/die-erste-ansicht-im-frontend where "JOOMLA4/index.php?option=com_foos&view=foo" is changed to SEF.

**Comment by pjdevries** [comment]
Yes, that's what I meant. Sorry for not being clear. When testing with SEF turned on, the menu link does not work, because we don't have a router yet :)

**Comment by astridx** [comment]
@pjdevries Thanks a lot. You are right. A hint is helpful here. I have added a note. This should be updated this night.

See: https://github.com/astridx/meinblog/commit/1a430043c2bbb85960395f15d42dfb7789096492#diff-9f3f77b73072c1dbaa96274c255be9e14d24c649a5f11aa5954f440acc37bb77
