### ISSUE TITLE
Buch: Erste Ansicht im Backend: postflight

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#19]
Buch:
Es ist erwähnenswert daß das Postflight nicht nur bei der Installation, sondern auch beim update / discover_install und bei **uninstall** aufgerufen wird.

[Doc J25: ](https://docs.joomla.org/J2.5:Developing_a_MVC_Component/Adding_an_install-uninstall-update_script_file)
```
	/**
	 * method to run after an install/update/uninstall method
	 *
	 * @return void
	 */
	function postflight($type, $parent) 

```
[Doc J3x:]( https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_an_install-uninstall-update_script_file)
Here it says **any** but does not mention uninstall.

```
  /**
     * Runs right after any installation action is performed on the component.
     *
     * @param  string    $type   - Type of PostFlight action. Possible values are:
     *                           - * install
     *                           - * update
     *                           - * discover_install
     * @param  \stdClass $parent - Parent object calling object.

```

**Uninstall** habe ich gerad noch mal geprüft.

**Comment by astridx** [comment]
Noch einmal Danke. Das habe ich nun richtig gestellt und die Hinweise ergänzt:

> Hinweis: In Joomla 3 haben nur Plugins die Preflight-Methode während des Deinstallationsprozesses aufgerufen und Postflight wurde nie bei der Deinstallation verwendet. Ab Version 4.0 sind diese beiden Hooks bei der Deinstallation für alle Erweiterungstypen verfügbar. Siehe [potenzielle Abwärtskompatibilitätsprobleme in Joomla 4](https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#CMS_Libraries)[^docs.joomla.org/Potenzielle_Abwärtskompatibilitätsprobleme_in_Joomla_4#CMS_Libraries].

> Möchtest du ganz genau wissen, wann welche Methode aufgerufen wird? Dann sieh dir die Datei `/libraries/src/Installer/InstallerAdapter.php` an. Die Befehle `$this->triggerManifestScript('');` starten die Ausführung der entsprechenden Methode.  Die `postflight`-Funktion wird beispielsweise via `$this->triggerManifestScript('postflight');` getriggert.
