### ISSUE TITLE
Buch: 48. Dark Mode ?window?.matchMedia

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#20]
48.1: ?window?.matchMedia

Im script wird matchMedia einmal mit 'windows.' und einmal ohne benutzt.
Braucht man das Object nicht oder es muss beides mal benutzt werden ?

**Comment by astridx** [comment]
Vielen Dank für den Hinweis.

Ich habe gerade den Text ergänzt:

> Fragst du dich, was `window.matchMedia` bedeutet? `window.variableName` bedeutet, dass die Variable `variableName` im globalen Bereich deklariert ist. Das bedeutet, dass jeder JavaScript-Code Zugriff auf diese Variable hat. Die Verwendung von `window` ist nicht zwingend erforderlich. [`window`](https://developer.mozilla.org/de/docs/Web/API/Window)[^developer.mozilla.org/de/docs/Web/API/Window] wird aber häufig als Konvention verwendet, um zu kennzeichnen, dass eine Variable global ist. Globale Variablen sind zu vermeiden. Sicherer ist es, wenn möglich eigene Variablen zu definieren.

Beim nächsten aktualisieren, geplant morgen, wird er im Blog erscheinen.
