### ISSUE TITLE
Buch 48.2: Diese CSS-Variablen ... 'durch'

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#21]
Der Satz "Diese CSS-Variablen ... " könnte folgendermaßen beginnen:

Diese CSS-Variablen werden durch das Javascript, welches ...

**Comment by astridx** [comment]
Vielen Dank für den Hinweis. Ich habe es etwas abgewandelt: "Diese CSS-Variablen werden via JavaScript, welches die Zeitzone abfragt, ein- und ausgeschaltet."
