### ISSUE TITLE
Joomla 4.x Tutorial - Komponente Pkt. 28 : doppeltes Bild 

### ISSUE THREAD

**Issue by jsr4id** [astridx/meinblog#33]
Im Tutorial Joomla 4.x unter Punkt 28 ist am Ende bei "Teste deine Joomla-Komponente" ein Bild doppelt, aber mit unterschiedlichen ALT Tag verlinkt.

[https://blog.astrid-guenther.de/joomla-featured/](https://blog.astrid-guenther.de/joomla-featured/)

**Comment by astridx** [comment]
Vielen Dank @jsr4id . Ich habe den Fehler in der deutschen Version gerade korrigiert. Das wird in den nächsten Tagen synchronisiert. 
In der englischen Version ist die Verlinkung schon jetzt richtig,.
