### ISSUE TITLE
Joomla 4.x-Tutorial: Pfad zu autoload_psr4.php

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#35]
Kapitel 2.4.5

Der Pfad zur Datei darf verbessert werden:
   joomla4x\administrator\cache\autoload_psr4.php

**Comment by astridx** [comment]
Wie meinst du das genau? Geht es um `joomla4x`?

**Comment by ThomasFinnern** [comment]
Das oben war vorsichtig ausgedrückt :-)

Bei joomla 4 ist der Pfad wie oben

**Comment by astridx** [comment]
Ja. Das ist OK, oder? Hier geht es ja nur um Joomla 4.

**Comment by ThomasFinnern** [comment]
Im buch ist es falsch, bei mir oben auch :-(

buch:
\administrator\library\autoload_psr4.php

in den sourcen gefunden:
librar*ies*
libraries\vendor\composer\autoload_psr4.php

**Comment by astridx** [comment]
Ach so. Ja, ich habe die Änderung des Speicherorts dieser Datei leider zu spät mitbekommen. Hier ist es aber schon länger korrekt: https://blog.astrid-guenther.de/joomla-tutorial-vorwort
