### ISSUE TITLE
Joomla 4.x-Tutorial: 2.4.13 Pfad von dateien

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#36]
Hier dürfte ed hilfreih sein wenn ein Beispiel angeführt würde.

Pfad: ...\media\com_foo\....

Damit die Nutzer nicht direkt in Media Dateien schreiben. ;-)

**Comment by astridx** [comment]
Ich hoffe ich habe es mit dieser Ergänzung verbessert:

> Beispiele: Für diese Tutorial-Erweiterung nutze ich später `media/com_foos/js/` für die JavaScript-Dateien der Komponente. Die CSS-Dateien des Modules `mod_articles_news` findest du im Verzeichnis `media/mod_articles_news/css/`. Und die Bilder zum Plugin `plg_content_vote` liegen im Ordner `media/plg_content_vote/images/`.
