### ISSUE TITLE
Joomla 4.x-Tutorial: Upper case variables used , lower case reseved

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#44]
24.1.2.5 HtmlView.php

protected state, params => definied lower case

... $this->"S"tate = $this>get('State')  ==> used upper case
... $this->"P"arams = $this>get('Params')  ==> used upper case

lower case should be used

**Comment by astridx** [comment]
Danke. Ich habe es gerade korrigiert.
