### ISSUE TITLE
Joomla 4.x-Tutorial: 25. Pagination -> model mit set state "list.limit"

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#45]
Gefühlt fehlt im Kapitel das Model mit set state 

->list.limit
-> list.start

Die müssen ja irgendwo gesetzt werde oder ?

**Comment by astridx** [comment]
Danke für den Hinweis. Ich habe das ergänzt:

> Hast du das Gefühl, dass in diesem Kapitel etwas fehlt? Fragst du dich, wo die ganzen Berechnungen stecken, welche die Seitenlink erstellen? Dann wirf ein einen Blick in die Datei [libraries/src/Pagination/Pagination.php](https://github.com/joomla/joomla-cms/blob/65aaacc28cddfed55804306eb02b407d28884159/libraries/src/Pagination/Pagination.php#L437)[^/github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Pagination/Pagination.php]. Joomla erledigt all die Arbeit für dich, wenn du den Standard nutzt und weißt wo du was findest.

**Comment by ThomasFinnern** [comment]
Sorry, so war das nicht gemeint

Beispiel:

d:\xampp\htdocs\joomla4x\components\com_content\src\Model\ArticlesModel.php 
protected function populateState ...

               // List state information
		$value = $app->input->get('limit', $app->get('list_limit', 0), 'uint');
		$this->setState('list.limit', $value);

		$value = $app->input->get('limitstart', 0, 'uint');
		$this->setState('list.start', $value); 

==> muss das gesetzt werden oder geht das auxh ohne  ? wann wird es benutzt

**Comment by astridx** [comment]
> ==> muss das gesetzt werden oder geht das auxh ohne ? wann wird es benutzt

Das wird in der Elternklasse des Models gesetzt.

https://github.com/astridx/meinblog/commit/bc5e1a0cc29dd07ee281433091d19b356f98c8c4#diff-fbac173052ae3e02136a4c0d062a02d02a608a380199087e33d67c1d56c6f969
