### ISSUE TITLE
Joomla 4.x-Tutorial: 26.1.2.3 Satz 

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#47]
components/com_foos/ src/View/Foo/HtmlView.php

Satz ?

Werden beispielsweise Elemente über eine Kategorie-Ansicht angezeigt, dass ist ein einheitliches Layout möglich

**Comment by astridx** [comment]
Danke. Ich habe es nun so geändert

> Im Falle eines Menüpunktes finde ich es wichtig, dass dieser - beziehungsweise der Inhalt und das Design- immer einheitlich angezeigt werden. Deshalb fragen wir den aktiven Menüpunkt ab. Werden beispielsweise Elemente über eine Kategorie-Ansicht angezeigt, dann ist mithilfe dieser Information ist ein einheitliches Layout möglich. Wird der Content als einzelnes Element angezeigt kann auf ein anderes Layout zurückgegriffen werden.

**Comment by ThomasFinnern** [comment]
Leider Satzbau ;-)

dann ist mithilfe dieser Information **ist** ein einheitliches Layout möglich

ist weglassen, dann gut

**Comment by astridx** [comment]
Noch einmal Danke schön :)
