### ISSUE TITLE
Joomla 4.x-Tutorial: Hilfe

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#49]
In diesem Abschnitt wird der Link zur Hilfeseite eingeführt.
Was ich vermisse ist wie die Hilfedatei aussieht und wo sie stehen muss.

Hab ich was übersehen ?

**Comment by astridx** [comment]
Es ist lediglich erforderlich, dass sie online über eine Adresse erreichbar sind. Ob du sie nutzt und wie du diese aufbaust, bleibt dir überlassen

https://github.com/astridx/meinblog/commit/bc5e1a0cc29dd07ee281433091d19b356f98c8c4#diff-8469f66f8fdc6f84328cba2c12d2741b6c6dae096de10241be0acbc1fc94ce8b
