### ISSUE TITLE
Joomla 4.x-Tutorial: path to presets missing in foo.xml

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/meinblog#50]
Entwicklung von Erweiterungen - Zugriff auf das Dashboard

Hier wird die Datei administrator/components/ com_foos/ presets/foos.xml hinzugefügt.

Das Verzeichnis presets muss dann in die Projekt XML eingefügt werden damit es installiert wird.

		<files folder="administrator/components/com_foo">
			<filename>access.xml</filename>
			<filename>changelog.xml</filename>
                        ...
			<folder>presets</folder>

**Comment by astridx** [comment]
Danke.
https://github.com/astridx/meinblog/commit/bc5e1a0cc29dd07ee281433091d19b356f98c8c4#diff-89d3ed533a1f09461def3f9d502ee56be624d247de2602eadad15d2b63ef4722
und 
https://github.com/astridx/boilerplate/commit/aa88ac35c6ead7c281e5d54c25807805b6f0a077
