### ISSUE TITLE
Links in "Joomla 4 - Developing Extensions" pdf are malformed

### ISSUE THREAD

**Issue by andriusbal** [astridx/meinblog#95]
Hello.

Links in footer are wrong, since the number of reference to the link is included in link itself and they do not work, e.g. link "8wikipedia.org/wiki/Git" is passed to browser as "http://8wikipedia.org/wiki/Git", so that "8" has to be deleted manually to visit desired link.
All other links in PDF are formatted the same way.

Best regards
Andrius

**Comment by astridx** [comment]
Thank you for your hint.
You must mean this place: https://blog.astrid-guenther.de/en/joomla/0vorwort/#code-editors-or-ide
I have corrected this in the latest version, which is unfortunately not yet ready.
